Scania:
  cuzov: "C:/Users/larle/toner_project/models/Scania-Cuzov.gltf"
  napolnitel: "C:/Users/larle/toner_project/models/Scania-Napolnitel.gltf"
  other: "C:/Users/larle/toner_project/models/Scania-Other.gltf"
  max_volume: 24
  ground_plane: 2.6

Kerax:
  cuzov: "C:/Users/larle/toner_project/models/Kerax-Cuzov.gltf"
  napolnitel: "C:/Users/larle/toner_project/models/Kerax-Napolnitel.gltf"
  other: "C:/Users/larle/toner_project/models/Kerax-Other.gltf"
  max_volume: 25
  ground_plane: 2.0

Kamaz:
  cuzov: "C:/Users/larle/toner_project/models/Kamaz-Cuzov.gltf"
  napolnitel: "C:/Users/larle/toner_project/models/Kamaz-Napolnitel.gltf"
  other: "C:/Users/larle/toner_project/models/Kamaz-Other.gltf"
  max_volume: 10
  ground_plane: 2.25

HooperType1:
  cuzov: "C:/Users/larle/toner_project/models/Hooper1-Cuzov.gltf"
  napolnitel: "C:/Users/larle/toner_project/models/Hooper1-Napolnitel.gltf"
  other: "C:/Users/larle/toner_project/models/Hooper1-Other.gltf"
  max_volume: 48
  ground_plane: 2.5

HooperType2:
  cuzov: "C:/Users/larle/toner_project/models/Hooper2-Cuzov.gltf"
  napolnitel: "C:/Users/larle/toner_project/models/Hooper2-Napolnitel.gltf"
  other: "C:/Users/larle/toner_project/models/Hooper2-Other.gltf"
  max_volume: 88
  ground_plane: 2.8